---
# tasks file for database
- name: Install required packages
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - wget
      - python3-psycopg2
      - acl
      - postgresql
      - postgresql-contrib

- name: Create postgres application user
  become: true
  become_user: postgres
  postgresql_user:
    name: 'counter'
    password: '{{ postgres_password }}'
    role_attr_flags: CREATEDB
    encrypted: yes
    state: present

- name: Configure postgresql conf
  copy:
    src: postgres.conf
    dest: /etc/postgresql/14/main/conf.d/counter.conf
    owner: postgres
    group: postgres
    mode: '0644'

- name: Configure pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/14/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0640'
