---
# handlers file for database
- name: Restart postgresql
  systemd:
    name: postgresql@14-main
    state: restarted

- name: Stop postgresql
  systemd:
    name: postgresql@14-main
    state: stopped

- name: Start postgresql
  systemd:
    name: postgresql@14-main
    state: started